# for the clusters
nb_users: 150
nb_movies: 200

# The cluster
nb_neighbour_users: 8
nb_neighbour_movies: 13

# The graph
proba_within_users: 0.8
proba_within_movies: 0.8

# The data
nb_ranked: 60
mean_good_ranked: 4
mean_bad_ranked: 2
variance_ranking: 0.5

# Hyperparameters
rate_test: 0.5
rate_training: 0.5

batch_size : 1
n_epoch : 2000
nb_iterations_rnn : 10
out_channels: 32
learning_rate: 1e-3
p_order_row: 5
p_order_col: 5
gamma: 1e-8


# Logging 
log_each : 20
log_level : INFO # DEBUG, INFO, WARNING, ERRO
tensorboard_dir : "runs"

# Reproductibility
seed : 42